### ISSUE TITLE
Headers already sent error  with Tabs::rememberActiveState() on Yii 2.0.14

### ISSUE THREAD

**Issue by mcabro** [dmstr/yii2-bootstrap#5]
https://github.com/dmstr/yii2-bootstrap/blob/07b42ef940ff50e011e5b250ac6cabbdae7dd431/Tabs.php#L41
Line 41 should use return instead of echo to avoid error with Yii > 2.0.14
            return "<script type='text/javascript'>{$js}</script>";

**Comment by eluhr** [comment]
Fixed in 0.2.2
